# Site settings
title: Kevin Lu
email: kevin.wen.lu@gmail.com
description: "Kevin is an instructor for the Internet of Things."
baseurl: ""
url: "http://kevinwlu.com"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
encoding: "UTF-8"
sass:
  style: :compressed

# Nav
navigation:
  - title: Posts
    url: /posts
  - title: Projects
    url: /projects
